---
kind: pipeline
name: matrix-1

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: ruby:latest
  commands:
  - bundle install
  - CODECOV_TOKEN=$CODECOV_SECRET bundle exec rake
  environment:
    CODECOV_SECRET:
      from_secret: codecov_secret
    GENERATE_REPORTS: true
