pipeline:
  build:
    image: ruby:${RUBY_VERSION}
    commands:
      - bundle install
      - GENERATE_REPORTS=true CODECOV_TOKEN=codecov_token bundle exec rake
    secrets: [ codecov_token ]

matrix:
  RUBY_VERSION:
    - latest
