pipeline:
  build:
    image: ruby:${RUBY_VERSION}
    commands:
      - bundle install
      - bundle exec rake

  matrix:
    RUBY_VERSION:
      - latest
      - "2.5"
      - "2.4"
      - "2.3"
      - "2.2"

