pipeline:
  build:
    image: ruby:${RUBY_VERSION}
    environment:
        - GENERATE_REPORTS=true
    secrets: [ codecov_secret ]
    commands:
      - bundle install
      - CODECOV_TOKEN=$CODECOV_SECRET bundle exec rake

matrix:
  RUBY_VERSION:
    - latest
